# Generated by Django 5.2 on 2025-04-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0003_remove_profile_password_remove_profile_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pending_loan', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
