# Generated by Django 5.2 on 2025-04-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0004_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='type',
            field=models.IntegerField(choices=[(1, 'Junior'), (2, 'Normal')], default=1),
        ),
    ]
