# Generated by Django 5.2 on 2025-04-25 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0010_loanplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='sacco.loanplan'),
        ),
    ]
