# Generated by Django 5.2 on 2025-04-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0012_loanproducttype_loanplan_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Auditor'), (3, 'Accountant'), (4, 'Supervisor'), (5, 'General Manager')], default=1),
        ),
    ]
