# Generated by Django 5.2 on 2025-04-28 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0013_alter_profile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_statements', to='sacco.member')),
            ],
        ),
    ]
