# Generated by Django 5.2 on 2025-04-28 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0014_savingstatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='sacco.loan')),
            ],
        ),
    ]
