# Generated by Django 5.2 on 2025-04-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0015_loanrepaymentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='category',
            field=models.CharField(choices=[('capital_share', 'Capital Share'), ('member_deposit', 'Member Deposit')], default='capital_share', max_length=20),
        ),
        migrations.AddField(
            model_name='saving',
            name='deposit_type',
            field=models.CharField(blank=True, choices=[('school_fees', 'School Fees'), ('vacation', 'Vacation'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
