# Generated by Django 5.2 on 2025-04-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0017_savingstatement_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
