# Generated by Django 5.2 on 2025-04-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0018_alter_loanrepayment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saving',
            old_name='note',
            new_name='receipt_no',
        ),
        migrations.AlterField(
            model_name='saving',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
