# Generated by Django 5.2 on 2025-04-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0019_rename_note_saving_receipt_no_alter_saving_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/bank_statements/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='current_payslip',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/payslips/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/id_documents/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
