# Generated by Django 5.2 on 2025-04-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0021_member_employment_status_member_fellowship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceOfIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='borrower',
            name='business_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='employer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='employer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='employer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-employed'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='sources_of_income',
            field=models.ManyToManyField(blank=True, to='sacco.sourceofincome'),
        ),
    ]
