# Generated by Django 5.2 on 2025-04-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0022_sourceofincome_borrower_business_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='guarantors',
            field=models.ManyToManyField(blank=True, related_name='guaranteed_borrowers', to='sacco.member'),
        ),
    ]
