# Generated by Django 5.2 on 2025-04-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0023_borrower_guarantors'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
