# Generated by Django 5.2 on 2025-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0024_loan_cheque_date_loan_cheque_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingstatement',
            name='deposit_type',
            field=models.CharField(blank=True, choices=[('school_fees', 'School Fees'), ('vacation', 'Vacation'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
    ]
