# Generated by Django 5.2 on 2025-04-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0026_alter_savingstatement_deposit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='deposit_type',
            field=models.CharField(choices=[('school_fees', 'School Fees'), ('vacation', 'Vacation'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
