# Generated by Django 5.2 on 2025-05-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0027_alter_saving_deposit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepaymentschedule',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
