# Generated by Django 5.2 on 2025-06-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0028_loanrepaymentschedule_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockedSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_locked', models.DateField(auto_now_add=True)),
                ('date_released', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_savings', to='sacco.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_savings', to='sacco.member')),
            ],
            options={
                'verbose_name': 'Locked Saving',
                'verbose_name_plural': 'Locked Savings',
                'ordering': ['-date_locked'],
            },
        ),
    ]
